export const countries = [
    { name: "Afghanistan", code: "+93", iso: "af" },
    { name: "Albania", code: "+355", iso: "al" },
    { name: "Algeria", code: "+213", iso: "dz" },
    { name: "Andorra", code: "+376", iso: "ad" },
    { name: "Angola", code: "+244", iso: "ao" },
    { name: "Argentina", code: "+54", iso: "ar" },
    { name: "Armenia", code: "+374", iso: "am" },
    { name: "Australia", code: "+61", iso: "au" },
    { name: "Austria", code: "+43", iso: "at" },
    { name: "Azerbaijan", code: "+994", iso: "az" },
    { name: "Bahrain", code: "+973", iso: "bh" },
    { name: "Bangladesh", code: "+880", iso: "bd" },
    { name: "Belarus", code: "+375", iso: "by" },
    { name: "Belgium", code: "+32", iso: "be" },
    { name: "Bhutan", code: "+975", iso: "bt" },
    { name: "Bolivia", code: "+591", iso: "bo" },
    { name: "Brazil", code: "+55", iso: "br" },
    { name: "Bulgaria", code: "+359", iso: "bg" },
    { name: "Cambodia", code: "+855", iso: "kh" },
    { name: "Cameroon", code: "+237", iso: "cm" },
    { name: "Canada", code: "+1", iso: "ca" },
    { name: "Chile", code: "+56", iso: "cl" },
    { name: "China", code: "+86", iso: "cn" },
    { name: "Colombia", code: "+57", iso: "co" },
    { name: "Costa Rica", code: "+506", iso: "cr" },
    { name: "Croatia", code: "+385", iso: "hr" },
    { name: "Cyprus", code: "+357", iso: "cy" },
    { name: "Czech Republic", code: "+420", iso: "cz" },
    { name: "Denmark", code: "+45", iso: "dk" },
    { name: "Dominican Republic", code: "+1", iso: "do" },
    { name: "Ecuador", code: "+593", iso: "ec" },
    { name: "Egypt", code: "+20", iso: "eg" },
    { name: "Estonia", code: "+372", iso: "ee" },
    { name: "Ethiopia", code: "+251", iso: "et" },
    { name: "Finland", code: "+358", iso: "fi" },
    { name: "France", code: "+33", iso: "fr" },
    { name: "Georgia", code: "+995", iso: "ge" },
    { name: "Germany", code: "+49", iso: "de" },
    { name: "Ghana", code: "+233", iso: "gh" },
    { name: "Greece", code: "+30", iso: "gr" },
    { name: "Hong Kong", code: "+852", iso: "hk" },
    { name: "Hungary", code: "+36", iso: "hu" },
    { name: "Iceland", code: "+354", iso: "is" },
    { name: "India", code: "+91", iso: "in" },
    { name: "Indonesia", code: "+62", iso: "id" },
    { name: "Iran", code: "+98", iso: "ir" },
    { name: "Iraq", code: "+964", iso: "iq" },
    { name: "Ireland", code: "+353", iso: "ie" },
    { name: "Israel", code: "+972", iso: "il" },
    { name: "Italy", code: "+39", iso: "it" },
    { name: "Jamaica", code: "+1", iso: "jm" },
    { name: "Japan", code: "+81", iso: "jp" },
    { name: "Jordan", code: "+962", iso: "jo" },
    { name: "Kazakhstan", code: "+7", iso: "kz" },
    { name: "Kenya", code: "+254", iso: "ke" },
    { name: "Kuwait", code: "+965", iso: "kw" },
    { name: "Latvia", code: "+371", iso: "lv" },
    { name: "Lebanon", code: "+961", iso: "lb" },
    { name: "Libya", code: "+218", iso: "ly" },
    { name: "Lithuania", code: "+370", iso: "lt" },
    { name: "Luxembourg", code: "+352", iso: "lu" },
    { name: "Malaysia", code: "+60", iso: "my" },
    { name: "Maldives", code: "+960", iso: "mv" },
    { name: "Malta", code: "+356", iso: "mt" },
    { name: "Mexico", code: "+52", iso: "mx" },
    { name: "Monaco", code: "+377", iso: "mc" },
    { name: "Mongolia", code: "+976", iso: "mn" },
    { name: "Morocco", code: "+212", iso: "ma" },
    { name: "Myanmar", code: "+95", iso: "mm" },
    { name: "Nepal", code: "+977", iso: "np" },
    { name: "Netherlands", code: "+31", iso: "nl" },
    { name: "New Zealand", code: "+64", iso: "nz" },
    { name: "Nigeria", code: "+234", iso: "ng" },
    { name: "Norway", code: "+47", iso: "no" },
    { name: "Oman", code: "+968", iso: "om" },
    { name: "Pakistan", code: "+92", iso: "pk" },
    { name: "Panama", code: "+507", iso: "pa" },
    { name: "Peru", code: "+51", iso: "pe" },
    { name: "Philippines", code: "+63", iso: "ph" },
    { name: "Poland", code: "+48", iso: "pl" },
    { name: "Portugal", code: "+351", iso: "pt" },
    { name: "Qatar", code: "+974", iso: "qa" },
    { name: "Romania", code: "+40", iso: "ro" },
    { name: "Russia", code: "+7", iso: "ru" },
    { name: "Saudi Arabia", code: "+966", iso: "sa" },
    { name: "Singapore", code: "+65", iso: "sg" },
    { name: "South Africa", code: "+27", iso: "za" },
    { name: "South Korea", code: "+82", iso: "kr" },
    { name: "Spain", code: "+34", iso: "es" },
    { name: "Sri Lanka", code: "+94", iso: "lk" },
    { name: "Sweden", code: "+46", iso: "se" },
    { name: "Switzerland", code: "+41", iso: "ch" },
    { name: "Taiwan", code: "+886", iso: "tw" },
    { name: "Thailand", code: "+66", iso: "th" },
    { name: "Turkey", code: "+90", iso: "tr" },
    { name: "Ukraine", code: "+380", iso: "ua" },
    { name: "United Arab Emirates", code: "+971", iso: "ae" },
    { name: "United Kingdom", code: "+44", iso: "gb" },
    { name: "USA", code: "+1", iso: "us" },
    { name: "Vietnam", code: "+84", iso: "vn" }
];